//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.Cat_food_map = new HashSet<Cat_food_map>();
        }
    
        public int Category_Id { get; set; }
        public string Category_name { get; set; }
        public bool Isactive { get; set; }
    
        public virtual ICollection<Cat_food_map> Cat_food_map { get; set; }
    }
}
