//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Order_Id { get; set; }
        public int UserId { get; set; }
        public int Res_food_mId { get; set; }
        public System.DateTime Order_DT { get; set; }
        public int Is_delivered { get; set; }
        public Nullable<System.DateTime> Delivery_DT { get; set; }
    
        public virtual Res_food_map Res_food_map { get; set; }
        public virtual user user { get; set; }
    }
}
