//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Res_food_map
    {
        public Res_food_map()
        {
            this.comments = new HashSet<comment>();
            this.Orders = new HashSet<Order>();
        }
    
        public int Res_food_mId { get; set; }
        public int Resturant_Id { get; set; }
        public int Item_Id { get; set; }
        public int Cost { get; set; }
        public Nullable<System.TimeSpan> Avail_From { get; set; }
        public Nullable<System.TimeSpan> Avail_to { get; set; }
        public int No_time_Sold { get; set; }
    
        public virtual ICollection<comment> comments { get; set; }
        public virtual FoodItem FoodItem { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual Restaurant Restaurant { get; set; }
    }
}
