//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public Role()
        {
            this.users = new HashSet<user>();
        }
    
        public int Role_Id { get; set; }
        public string Rolename { get; set; }
        public bool Isactive { get; set; }
    
        public virtual ICollection<user> users { get; set; }
    }
}
