//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class cuisine
    {
        public cuisine()
        {
            this.FoodItems = new HashSet<FoodItem>();
        }
    
        public int Cuisine_Id { get; set; }
        public string cuisine_name { get; set; }
        public int Cuisine_level { get; set; }
        public Nullable<int> parent { get; set; }
    
        public virtual ICollection<FoodItem> FoodItems { get; set; }
    }
}
