//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Filter_cat_map
    {
        public int Filter_cat_map_id { get; set; }
        public int Filter_Id { get; set; }
        public int category_Id { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Filter Filter { get; set; }
    }
}
