//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodItem
    {
        public FoodItem()
        {
            this.Cat_food_map = new HashSet<Cat_food_map>();
            this.comments = new HashSet<comment>();
            this.Res_food_map = new HashSet<Res_food_map>();
        }
    
        public int Item_Id { get; set; }
        public string Item_name { get; set; }
        public Nullable<int> Cusine_Id { get; set; }
        public int No_time_sold { get; set; }
        public bool Is_street { get; set; }
        public Nullable<bool> isVeg { get; set; }
    
        public virtual ICollection<Cat_food_map> Cat_food_map { get; set; }
        public virtual ICollection<comment> comments { get; set; }
        public virtual cuisine cuisine { get; set; }
        public virtual ICollection<Res_food_map> Res_food_map { get; set; }
    }
}
