//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public Location()
        {
            this.Restaurants = new HashSet<Restaurant>();
        }
    
        public int Location_Id { get; set; }
        public string Location_name { get; set; }
        public int city_Id { get; set; }
        public int Zipcode { get; set; }
    
        public virtual City City { get; set; }
        public virtual ICollection<Restaurant> Restaurants { get; set; }
    }
}
